version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: devperion-padloc-server_pwa_1
      APP_PORT: 8080

  server:
    image: padloc/server:latest
    init: true
    environment:
      PL_DATA_BACKEND: leveldb
      PL_DATA_LEVELDB_DIR: /data
      PL_DATA_ATTACHMENTS_BACKEND: fs
      PL_DATA_ATTACHMENTS_DIR: /attachments
      PL_SERVER_CLIENT_URL: http://localhost:8080
      PL_EMAIL_BACKEND: console
    volumes:
      - ${APP_DATA_DIR}/attachments:/attachments
      - ${APP_DATA_DIR}/data:/data
    restart: unless-stopped

  pwa:
    image: padloc/pwa:latest
    init: true
    depends_on:
      - server
    environment:
      PL_SERVER_URL: http://server:3000
      PL_PWA_URL: http://localhost:8080
    restart: unless-stopped